version: '3'

services:
  app:
    image: farmmanager:latest
    volumes:
      - ./data:/app/data
    restart: "always"
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      Jwt__Key: 'M9CWD+d8TKbGn44J2LxWlZUx4SF0/743yIwgLKl34V0='
      Jwt__RKey: '7CAAUB7rvLN/fzPYk+rKT8WOU6sVjC/BZTKoVZ5eXV4='
      Jwt__Issuer: 'https://api.example.com'
      Jwt__Audience: 'https://example.com'
      Jwt__Secure: 'false'
      Jwt__SSM: 'Lax'
      Cors__Origin: 'https://example.com'
      UseHttpsRedirection: 'false'
      ASPNETCORE_ENVIRONMENT: 'Production'
      ASPNETCORE_URLS: 'http://+:5005'
      FRONTEND_PORT: '3005'
